version: 0.2
phases:
  install:
    commands:
      - npm install

  pre_build:
    commands:
      - npm run lint
      - npm run compile
      - npm prune --production
  build:
    commands:
      - sam package --template template.yml --s3-bucket global-resources-881463952688 --s3-prefix sam/hello-world/default/ --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
