version=0.1
[default.global.parameters]

[default.deploy.parameters]
stack_name = "sam-hello-world"
s3_bucket = "brainstation-081656289929-ap-southeast-2"
s3_prefix = "sam/hello-world"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
tags = "project=\"hello-world\" stage=\"default\""
fail_on_empty_changeset = false
